[package]
name = "audiolyzer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cpal = "0.13.3"
tui = "0.17.0"
crossterm = "0.23.2"
realfft = "3.0.0"
apodize = "1.0.0"